# email_bot.py
"""
Email Integration — Real-World Messaging Channel for the Agentic RAG Bot.

How it works:
  1. Polls a Gmail (or any IMAP) inbox every 60 seconds.
  2. Looks for UNREAD emails whose Subject contains the tag "[RAG]".
  3. Pipes the email body into run_supervisor_agent().
  4. Replies to the sender with the agent's answer via SMTP.
  5. Marks the email as READ so it won't be processed again.

Setup (Gmail):
  1. Enable "Less secure app access" OR create an App Password at
     https://myaccount.google.com/apppasswords
  2. Add these keys to your .env file:
       EMAIL_ADDRESS=yourbot@gmail.com
       EMAIL_PASSWORD=your_app_password_here
       IMAP_SERVER=imap.gmail.com
       SMTP_SERVER=smtp.gmail.com
       SMTP_PORT=587
  3. Run:  python app/email_bot.py

The bot runs indefinitely. Press Ctrl+C to stop.

Note: HITL approval is disabled in email mode (user_confirmation_callback=None)
because there's no interactive session. Write-tool actions are auto-approved.
If you want approval gates via email, use a two-email round-trip pattern
(bot sends draft → user replies "approve" → bot executes). That's left as an
extension for now.
"""

import imaplib
import smtplib
import email
import time
import os
import sys
import textwrap
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import decode_header
from dotenv import load_dotenv

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

from app.agents import run_supervisor_agent

# ── Config from .env ──────────────────────────────────────────────────────────
EMAIL_ADDRESS  = os.getenv("EMAIL_ADDRESS", "")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD", "")
IMAP_SERVER    = os.getenv("IMAP_SERVER",   "imap.gmail.com")
SMTP_SERVER    = os.getenv("SMTP_SERVER",   "smtp.gmail.com")
SMTP_PORT      = int(os.getenv("SMTP_PORT", "587"))

POLL_INTERVAL  = 60   # seconds between inbox checks
SUBJECT_FILTER = "[RAG]"  # only process emails whose subject contains this tag


# ── Email utilities ───────────────────────────────────────────────────────────

def _decode_header_value(raw: str) -> str:
    """Decode RFC2047-encoded email headers into a plain string."""
    parts = decode_header(raw)
    decoded = []
    for part, charset in parts:
        if isinstance(part, bytes):
            decoded.append(part.decode(charset or "utf-8", errors="replace"))
        else:
            decoded.append(part)
    return "".join(decoded)


def _extract_body(msg: email.message.Message) -> str:
    """Extract plain-text body from an email.message.Message."""
    if msg.is_multipart():
        for part in msg.walk():
            if part.get_content_type() == "text/plain":
                charset = part.get_content_charset() or "utf-8"
                return part.get_payload(decode=True).decode(charset, errors="replace")
    else:
        charset = msg.get_content_charset() or "utf-8"
        return msg.get_payload(decode=True).decode(charset, errors="replace")
    return ""


def _send_reply(to_address: str, subject: str, body: str) -> None:
    """Send a plain-text reply via SMTP."""
    reply_subject = subject if subject.startswith("Re:") else f"Re: {subject}"

    msg = MIMEMultipart("alternative")
    msg["From"]    = EMAIL_ADDRESS
    msg["To"]      = to_address
    msg["Subject"] = reply_subject

    # Plain text version
    msg.attach(MIMEText(body, "plain", "utf-8"))

    # HTML version — simple formatting
    html_body = body.replace("\n", "<br>")
    html = f"""
    <html><body style="font-family: Arial, sans-serif; line-height: 1.6;">
    <div style="max-width: 680px; margin: auto; padding: 20px;">
        <h3 style="color: #6366f1;">🧠 Manikanta AI — Response</h3>
        <hr style="border-color: #e5e7eb;">
        <p>{html_body}</p>
        <hr style="border-color: #e5e7eb;">
        <p style="font-size: 12px; color: #9ca3af;">
            This reply was generated by the Agentic RAG system.
            Reply with a new <b>[RAG]</b> email to ask another question.
        </p>
    </div>
    </body></html>
    """
    msg.attach(MIMEText(html, "html", "utf-8"))

    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        server.sendmail(EMAIL_ADDRESS, to_address, msg.as_string())

    print(f"  ✉️  Reply sent to {to_address}")


# ── Inbox polling ─────────────────────────────────────────────────────────────

def process_inbox() -> None:
    """
    Connect to IMAP, find unread [RAG] emails, process each one, reply, mark read.
    """
    try:
        mail = imaplib.IMAP4_SSL(IMAP_SERVER)
        mail.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        mail.select("INBOX")

        # Search for UNREAD emails
        status, data = mail.search(None, "UNSEEN")
        if status != "OK" or not data[0]:
            mail.logout()
            return

        email_ids = data[0].split()
        print(f"[EmailBot] Found {len(email_ids)} unread email(s).")

        for eid in email_ids:
            # Fetch the email
            status, msg_data = mail.fetch(eid, "(RFC822)")
            if status != "OK":
                continue

            raw_email = msg_data[0][1]
            msg = email.message_from_bytes(raw_email)

            subject    = _decode_header_value(msg.get("Subject", ""))
            from_addr  = _decode_header_value(msg.get("From", ""))
            reply_to   = msg.get("Reply-To") or from_addr

            # Only process emails with the [RAG] tag
            if SUBJECT_FILTER.lower() not in subject.lower():
                print(f"  ⏭  Skipping (no {SUBJECT_FILTER} tag): {subject!r}")
                continue

            body = _extract_body(msg).strip()
            if not body:
                print(f"  ⏭  Skipping empty email from {from_addr}")
                continue

            print(f"  📩 Processing email from {from_addr}: {subject!r}")
            print(f"     Query: {body[:100]}...")

            # ── Run the agent ──────────────────────────────────────────────
            try:
                answer = run_supervisor_agent(
                    user_prompt=body,
                    user_confirmation_callback=None,  # auto-approve in email mode
                )
            except Exception as e:
                answer = f"Sorry, the agent encountered an error: {e}"

            # ── Reply ──────────────────────────────────────────────────────
            _send_reply(reply_to, subject, answer)

            # ── Mark as READ (\\Seen flag) ─────────────────────────────────
            mail.store(eid, "+FLAGS", "\\Seen")

        mail.logout()

    except imaplib.IMAP4.error as e:
        print(f"[EmailBot] IMAP error: {e}")
    except smtplib.SMTPException as e:
        print(f"[EmailBot] SMTP error: {e}")
    except Exception as e:
        print(f"[EmailBot] Unexpected error: {e}")


# ── Main loop ─────────────────────────────────────────────────────────────────

def run_email_bot() -> None:
    """Start the email bot polling loop."""
    if not EMAIL_ADDRESS or not EMAIL_PASSWORD:
        print(
            "❌  EMAIL_ADDRESS and EMAIL_PASSWORD must be set in your .env file.\n"
            "    See the docstring at the top of email_bot.py for setup instructions."
        )
        sys.exit(1)

    print("=" * 60)
    print(" 📬  Manikanta AI — Email Bot")
    print("=" * 60)
    print(f"  Account  : {EMAIL_ADDRESS}")
    print(f"  IMAP     : {IMAP_SERVER}")
    print(f"  SMTP     : {SMTP_SERVER}:{SMTP_PORT}")
    print(f"  Filter   : Subject must contain '{SUBJECT_FILTER}'")
    print(f"  Interval : {POLL_INTERVAL}s")
    print("-" * 60)
    print("  Send emails with '[RAG] Your question here' as the subject.")
    print("  The bot will reply within 60 seconds.")
    print("  Press Ctrl+C to stop.\n")

    while True:
        try:
            print(f"[EmailBot] Checking inbox at {time.strftime('%H:%M:%S')}...")
            process_inbox()
        except KeyboardInterrupt:
            print("\n[EmailBot] Stopped.")
            break
        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    run_email_bot()
